### PR TITLE
feat: add matching fund fields

### LINKED ISSUE #513: Add Matching Fund fields to Round Details (happy path)
**User Story:**
As a round operator
I want to configure the quadratic funding settings for my round
So that the mechanism fits my needs

**Acceptance Criteria**
GIVEN that I am on the Round Details step of the round creation flow
WHEN I look at the Quadratic Funding Settings section
THEN I see text fields for "Matching Funds Available" and the matching cap percentage
AND a yes / no button for adding a matching cap to projects 

GIVEN that I am on the Round Details step
WHEN I hover over the Matching Cap yes/no tool tip
THEN I see the tooltip copy

GIVEN that I am on the Round Details step
WHEN I enter an amount in Matching Funds Available
THEN the field shows the selected token symbol as the unit (i.e. 20,000 DAI)

GIVEN that I am on the Round Details step
WHEN I enter an amount in the Matching Cap field
THEN I see a percent symbol next to the number
AND the Yes matching cap button is checked

GIVEN that I have filled out the required Quadratic Funding Settings
WHEN I deploy the round
THEN my settings are saved to IPFS

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2193%3A15103)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### LINKED ISSUE #570: Add Matching Fund fields to Round Details (sad path)
Depends on #513 

**User Story:**
As a round operator
I want to configure the quadratic funding settings for my round
So that the mechanism fits my needs

**Acceptance Criteria**
GIVEN that I am on the Round Details step and have entered a non-numeric value in the Matching Funds Available field
WHEN I click off the field
THEN I see an error message that matching funds must be numeric values

GIVEN that I am on the Round Details step and have entered a non-numeric value in the Matching Cap field
WHEN I click off the field
THEN I see an error message that matching caps must be numeric values

GIVEN that I am on Round Details and have not selected Yes or No for a matching cap
WHEN I click Next
THEN I see an error message that I must select yes or no

GIVEN that I am on Round Details and have selected Yes for a matching cap
WHEN I click Next and do not have all three required text fields filled in (Payout Token, Matching Funds, Matching Cap)
THEN I see an error message that required fields must be entered

GIVEN that I am on Round Details and have selected No for a matching cap
WHEN I click Next and do not have the two required text fields filled in (Payout Token, Matching Funds)
THEN I see an error message that required fields must be entered

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2193%3A15103)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
##### Description

As a round operator
I want to configure the quadratic funding settings for my round
So that the mechanism fits my needs

##### Refers/Fixes

fixes #513, fixes #570

### CODE REVIEW

**Review by shavinac — APPROVED** [review]

**Review by melissa-neira — CHANGES_REQUESTED** [review]
hey guys, this might be my browser but things are looking a little funky here:
Screen Shot 2022-10-28 at 17 15 05
Screen Shot 2022-10-28 at 17 17 38
is there any way to not make that % sign static? can the text itself be formatted to be a percentage itself? kind of like "10%" instead of "10__________ %"?

<br>
also, these boxes are looking a little funky as well (but again, might be my browser)
Screen Shot 2022-10-28 at 17 21 37
text is cut off - should look like this:
Screen Shot 2022-10-28 at 17 22 09

and when a payout token is selected that box looks like this:
Screen Shot 2022-10-28 at 17 21 47
the text is all jumbled up. 

sorry if this is a lot! I'd appreciate other eyes on this just to make sure this is not me (I tried it on 2 browsers and the same thing happened)
let me know if I can clear anything up.

**Comment by melissa-neira** [comment]
One more thing - those fields are currently marked as required in the design but are not currently in the preview. Here's a link to what that's supposed to look like:
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2355%3A14680)

**Review by thelostone-mc — APPROVED** [review]

**Comment by hmrtn** [comment]
@melissa-neira There is no 'simple' way of adding a percentage or currency suffix to the input fields without touching the event handler. However, we can prepend the symbols to the beginning of the fields like so for a simple fix. thoughts? 
Screen Shot 2022-10-31 at 9 33 54 AM

**Comment by melissa-neira** [comment]
@hmrtn that looks good to me!

**Comment by melissa-neira** [comment]
@hmrtn just noticed - the height of the matching funds available box is slightly smaller than the rest of the boxes. can we make sure all boxes are H- 40px and W- 386px

**Review by hmrtn — APPROVED** [review]

**Review by nfrgosselin — APPROVED** [review]

**Review by nfrgosselin — APPROVED** [review]

**Review by melissa-neira — APPROVED** [review]

**Pull request merged**
