### PR TITLE
Update website title and favicons

### PR DESCRIPTION
**Pull request by shavinac**
- update GE webpage title to "Gitcoin | Grant Explorer"
- update favicons for GE and RM to match navbar logos, replacing default React favicon

Round Manager browser tab
Grant Explorer browser tab

### CODE REVIEW

**Review by nfrgosselin — APPROVED** [review]

**Review by melissa-neira — CHANGES_REQUESTED** [review]
Can we change these logos to pngs or svgs? (to make the background transparent?) the black & white backgrounds are triggering me 😂 let me know which file format you need (& what size) and I'll provide you with the correct files

**Comment by shavinac** [comment]
> Can we change these logos to pngs or svgs? (to make the background transparent?) the black & white backgrounds are triggering me 😂 let me know which file format you need (& what size) and I'll provide you with the correct files

Would you be able to get logos in 64x64 .ico or PNG files?

**Comment by melissa-neira** [comment]
> > Can we change these logos to pngs or svgs? (to make the background transparent?) the black & white backgrounds are triggering me 😂 let me know which file format you need (& what size) and I'll provide you with the correct files
> 
> Would you be able to get logos in 64x64 .ico or PNG files?

Here you go🌟 the RM logo has been updated but not sure if finalized yet - use this placeholder for now.
GE
RM

**Comment by shavinac** [comment]
> Here you go🌟 the RM logo has been updated but not sure if finalized yet - use this placeholder for now.

Thank you, previews are updated with new favicons!

**Review by melissa-neira — APPROVED** [review]
looks 🔥 thank you!

**Pull request merged**
