### PR TITLE
feat(ge): see project details

### LINKED ISSUE #352: See Project Details in GE
_Note: user does not need to connect their wallet for this_

**User Story:**
As a voter
I want to see more details about projects in the round
So that I can make an informed decision about whether I should vote for them

**Acceptance Criteria**
GIVEN that I am on the Grant Explorer main page
WHEN I click on a project card
THEN I am brought to that project's detail page within Grant Explorer

GIVEN that I am on a GE project detail page
WHEN I look at the page
THEN I see the required detail data in the given layout (see list of data and mocks below)

GIVEN that I am on a GE project detail page
WHEN I click on the "back to grants" button
THEN I am brought back to the GE main page

Required detail data:
- Project banner
- Project logo
- Project name
- website
- twitter
- project description

**Product & Design Links:**
- [Miro mock](https://miro.com/app/board/uXjVPYmqufs=/?moveToWidget=3458764532908599183&cot=14)
- [Figma link](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=295%3A2340)

**Tech Details:**
- Dependent on #351 

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by shavinac**
##### Description

See project details in Grant Explorer

- [x] create new route for project detail page
- [x] render project details in plain text
- [x] add "back to grants" button on project detail page
- [x] style project detail page

##### Refers/Fixes

fixes #352

### CODE REVIEW

**Comment by dschinkel** [comment]
Hold on the review, I forgot to add a section title for Project Desc

**Review by thelostone-mc — APPROVED** [review]

**Review by melissa-neira — COMMENTED** [review]
Does anyone have a link so I can see this in action? The preview link still just shows me the 404

**Comment by shavinac** [comment]
> Does anyone have a link so I can see this in action? The preview link still just shows me the 404

@melissa-neira try https://bafybeibsqzvsq27mrgn3r3dsa6uzekd4rqecrckihoogbkqoqoin5674je.on.fleek.co/#/round/5/0xe005f9bfabb61c2f04a08bf023044f9e1ed7dedd

if you have your own round with applications, you can see it on GE using the format `{...GE preview link...}/#/round/{chain id}/{round id}`

**Review by melissa-neira — CHANGES_REQUESTED** [review]
the project details page looks good to me, but for some reason, the nav bar is missing on the project details page. was this intentional? if not, pls fix 🤘

**Review by melissa-neira — APPROVED** [review]

**Review by nfrgosselin — APPROVED** [review]

**Pull request merged**
