### PR TITLE
feat: apply fixed donation amount

### LINKED ISSUE #490: Copy amount to other projects
**User Story:**
As a donor
I want to be able to apply an amount to all projects
So that I can easily make donation decisions

**Acceptance Criteria**
GIVEN that I am on the Donation Builder and have projects on my final donation
WHEN I look at the top of the final donation
THEN I see the "Amount / Currency" numeric entry field
AND a "Apply to All" button

GIVEN that I have entered an amount in the "Amount / Currency" numeric entry field
WHEN I click "Apply to All"
THEN that amount is copied to all the projects in my final donation
AND the "Your Contribution" summary amount updates

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1055%3A27643)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
##### Description

As a donor
I want to be able to apply an amount to all projects
So that I can easily make donation decisions

##### Refers/Fixes

fixes #490

### CODE REVIEW

**Comment by vacekj** [comment]
I ask forgiveness for my sin of Merging instead of Rebasing, for the conflicts have proven too difficult to resolve by rebasing.

**Review by nfrgosselin — CHANGES_REQUESTED** [review]
The first AC works (copying the amount to the line item), but the Your Contribution sum doesn't update

https://www.loom.com/share/13db7935cf634b2db68853de0d5d4d7c

**Comment by vacekj** [comment]
> The first AC works (copying the amount to the line item), but the Your Contribution sum doesn't update
> 
> [loom.com/share/13db7935cf634b2db68853de0d5d4d7c](https://www.loom.com/share/13db7935cf634b2db68853de0d5d4d7c)

Thanks, fixed.

**Review by melissa-neira — CHANGES_REQUESTED** [review]
The amount/currency module should be aligned to the right along with the other components beneath it. This is what I see on my end currently:
Screen Shot 2022-11-16 at 11 22 43

Here's what it should look like [Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1583%3A63811)

Other than that, it works well!

**Review by melissa-neira — APPROVED** [review]

**Review by nfrgosselin — APPROVED** [review]

**Review by hmrtn — APPROVED** [review]

**Pull request merged**
