### PR TITLE
feat(ge): remove project from shortlist

### PR DESCRIPTION
**Pull request by chibie**
##### Description

This PR adds the functionality to remove project from shortlist

- [x] add trash icon click event
- [x] add test cases: show icon, remove item

### CODE REVIEW

**Review by thelostone-mc — CHANGES_REQUESTED** [review]
codewise lgtm but commit history needs to be cleaned up

**Review by thelostone-mc — APPROVED** [review]

**Review by thelostone-mc — CHANGES_REQUESTED** [review]
Ignore this

**Review by thelostone-mc — APPROVED** [review]

**Review by melissa-neira — APPROVED** [review]

**Review by nfrgosselin — CHANGES_REQUESTED** [review]
The functionality works for me, but can we make the icon hover state friendlier to match our other icon states?

https://www.loom.com/share/5b5f9fcc4f944916ba9c0fb9365f585b

**Comment by thelostone-mc** [comment]
@nfrgosselin / @melissa-neira Could you show us what the hover states looks like ?

**Pull request merged**
