### PR TITLE
feat: markdown support

### LINKED ISSUE #973: feat: display content from Hub WYSIWYG editor
### Description

Wire in markdown rendering for the following components:

**Round Manager**
- [x] Page where you can review an individual project application
- [x] Page where you can review all project applications

**Grant Explorer**
- [x] Page where you can review an individual project taking part in the round
- [x] Page where you can review all projects in the round
- [x] Page where you cast your donations

Additionally:
- [x] Use Tailwind Typograhy and mark those components as prose to get nice formatting for free

### PR DESCRIPTION
**Pull request by vacekj**
This PR adds capability to RM and GE to display markdown-formatted rich text. This impacts a few places, mentioned in the issue #973. It also adds a function to strip markdown tags to display the source text in small spaces. For more docs, see the `markdown.ts` file.

fixes #973

### CODE REVIEW

**Comment by thelostone-mc** [comment]
Changes look sane but conflicts need to be resolved and could you drop in a more detail description on what changes have been made and why for context ?

**Comment by melissa-neira** [comment]
defer to engineers 💯

**Comment by vacekj** [comment]
@thelostone-mc added a description, comments in code (only in one copy, as those will be merged anyway).

**Review by bhargavaparoksham — CHANGES_REQUESTED** [review]
@vacekj This is how project description in our alpha rounds look with markdown & without markdown.

Without markdown:
Screenshot 2023-01-25 at 11 12 59 PM

With markdown:
Screenshot 2023-01-25 at 11 10 23 PM

Is there anything we can do to add the line breaks if there are no line breaks, so that project description is formatted correctly?

**Comment by vacekj** [comment]
@bhargavaparoksham thanks for noticing, this is now fixed. line breaks in the source text will result in a single line break (not double unlike previously, which I assume was a bug) now.

**Review by bhargavaparoksham — APPROVED** [review]

**Pull request merged**
