### PR TITLE
chore: update applyToRound applications

### PR DESCRIPTION
**Pull request by chibie**
##### Description

This PR updates the applyToRound function with the latest structure for grant applications

##### Testing

https://ipfs.fleek.co/ipfs/bafybeiceggy6uzfxsn3z6b2rraptp3g2kx2nrwailkjnx522yah43g5tyu

https://ipfs.fleek.co/ipfs/bafybeih2pise44gkkzj7fdws3knwotppnh4x2gifnbxjtttuv7okw4mjzu

https://ipfs.fleek.co/ipfs/bafybeiekytxwrrfzxvuq3ge5glfzlhkuxjgvx2qb4swodhqd3c3mtc5jay

### CODE REVIEW

**Comment by QEDK** [comment]
> ##### Description
> 
> This PR updates the applyToRound function with the latest structure for grant applications
> ##### Refers/Fixes
> ##### Testing
> 
> https://ipfs.fleek.co/ipfs/bafybeiceggy6uzfxsn3z6b2rraptp3g2kx2nrwailkjnx522yah43g5tyu
> 
> https://ipfs.fleek.co/ipfs/bafybeih2pise44gkkzj7fdws3knwotppnh4x2gifnbxjtttuv7okw4mjzu
> 
> https://ipfs.fleek.co/ipfs/bafybeiekytxwrrfzxvuq3ge5glfzlhkuxjgvx2qb4swodhqd3c3mtc5jay

before I can approve this, can you give me an older hash so I can do a differential check and know what I am supposed to be looking for.

**Comment by chibie** [comment]
@QEDK here's a former hash https://ipfs.fleek.co/ipfs/bafybeig5focgmbzugeyh6bd2inhuhqcflw4mcsqcovbu5lomjkou5unl6u

the new one is based on this https://github.com/gitcoinco/grants-round/discussions/172

**Review by thelostone-mc — APPROVED** [review]
checked :D

**Review by QEDK — APPROVED** [review]
LGTM.

**Pull request merged**
