### PR TITLE
feat: change invalid passport message

### LINKED ISSUE #983: Change Invalid Passport language
**Details**
The current "Invalid Passport" banner language is misleading, as it sounds like the user has an error if they don't have their Passport set up. We want to change the language.

**Acceptance Criteria**
GIVEN that the user has connected their wallet
WHEN the Passport API returns a 400 error
THEN the banner reads "Passport score not detected. Please configure your Passport."
AND "Please configure your passport" is a link to the Explorer's Passport verification page

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by vacekj**
fixes #983 

##### Description

changes wording on invalid passport banner

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]

**Comment by vacekj** [comment]
@nfrgosselin Thanks, fixed!

**Comment by melissa-neira** [comment]
Hey, since this wasn't in any of the designs, I changed the colors a bit and added an icon to make sure this compiles with our design system. The banner in its current state clashes a bit with the rest of our designs. 
Design here - [Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=3079%3A80543&t=5kWJAciWNrVJNpcE-4)

**Comment by vacekj** [comment]
@melissa-neira @nfrgosselin fixed and edited design

**Review by nfrgosselin — APPROVED** [review]
I'm approving based on a screenshare with @vacekj

**Pull request merged**
