### PR TITLE
feat: build skeleton and implement /calculate endpoint

### LINKED ISSUE #381: Calculate single vote
**User Story:**
As a QF smart contract
I want to send my votes to an offchain calculation service
So that my funding allocation can be allocated cheaply

**Acceptance Criteria**
GIVEN that I have data for one vote
WHEN I send that vote to the calculation app
THEN I receive the results based on that one vote

**Product & Design Links:**
- [Flow in Miro](https://miro.com/app/board/uXjVPY3Csls=/?moveToWidget=3458764532978275196&cot=14)
- Don't worry about persisting results at this point
- Assuming that this is building the calculation component
- This does not include pulling data from the subgraph

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### LINKED ISSUE #382: Calculate all votes
**User Story:**
As a QF smart contract
I want to send my votes to an offchain calculation service
So that my funding allocation can be allocated cheaply

**Acceptance Criteria**
GIVEN that I have sent >=1 votes to the calculation app
WHEN I send another vote to the app
THEN I receive the results based on all votes

**Product & Design Links:**
- [Flow in Miro](https://miro.com/app/board/uXjVPY3Csls=/?moveToWidget=3458764532978275196&cot=14)
- Data needs to be persisted
- Can assume that all votes are part of the same round at this point

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by hmrtn**
fixes #381 
fixes #382

This implements the `/calculate` endpoint into the API gateway. 

It calculates a matching amount for the contribution based on the project identifier.

To test - make a POST request with the following JSON body: 
```json
[
    {
        "projectId": "project1", 
        "amount": 10, 
        "contributor": "0x001...",
        "timestamp": 0
    }, 
    {
        "projectId": "project1", 
        "amount": 25, 
        "contributor": "0x001...",
        "timestamp": 0
    }, 
    {
        "projectId": "project2", 
        "amount": 99, 
        "contributor": "0x666...",
        "timestamp": 0
    },
        {
        "projectId": "project2", 
        "amount": 3, 
        "contributor": "0x888...",
        "timestamp": 0
    }
]
```
And the response should be list of matching amounts grouped by their Id e.g. 

```json
{
    "distribution": [
        {
            "projectId": "project1",
            "match": 7.105427357601002e-15
        },
        {
            "projectId": "project2",
            "match": 48.74423042781572
        }
    ],
    "hasSaturated": false
}
```

What should error handling and logging look like? Suggestions welcome. 

Side note: we need to prioritize a testing framework with pulumi and aws.

### CODE REVIEW

**Comment by thelostone-mc** [comment]
<3

**Comment by thelostone-mc** [comment]
- We should add unit test cases 
- Also this is a solid starting point -> i don't think we would need to pass the contributions directly cause ideally given the chain ID and round ID, the script would be able to fetch this 

Then again it is nice to have an endpoint which calculates when the votes are manually sent in. Not sure about the usecase but it's def nice to have

**Comment by thelostone-mc** [comment]
https://12yy26d4q3.execute-api.us-east-1.amazonaws.com/stage/calculate

**Comment by melissa-neira** [comment]
I defer my review to engineering 🕺

**Comment by nfrgosselin** [comment]
Defer to engineering 🔧

**Review by thelostone-mc — APPROVED** [review]

**Pull request merged**
