### PR TITLE
chore: shortend description

### LINKED ISSUE #690: Shorten project description in Donation Builder
**User Story:**
As a user
I want to see a shorter description of a project
So that the UI of the Donation Builder doesn't look broken

**Acceptance Criteria**
GIVEN that a project is in either the Shortlist or Final Donation boxes
THEN the project's description is shortened to display 3 lines max

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1583%3A63811)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

restrict character limit to 130 characters in description

##### Refers/Fixes

fixes #690

### CODE REVIEW

**Review by bhargavaparoksham — APPROVED** [review]

**Review by nfrgosselin — APPROVED** [review]

**Review by melissa-neira — CHANGES_REQUESTED** [review]
Hey, I realized that I didn't put this in the AC (my bad) but can we please add some ellipses to the end of descriptions that get cut off?
Right now it looks like this and I think it would look cleaner if we added some ellipses in there to indicate a description has been cut off
Screen Shot 2022-11-18 at 10 10 21

**Comment by hmrtn** [comment]
To properly truncate text we should utilize tailwinds builtin feature: 

https://tailwindcss.com/docs/text-overflow

**Comment by vacekj** [comment]
@melissa-neira ellipsis should be added now

**Comment by melissa-neira** [comment]
It doesn't seem like ellipsis have been added on my end, could just be me though 😅
Screen Shot 2022-11-21 at 09 49 40
The same happens in the Final Donation box, but the description is much shorter.

**Review by melissa-neira — CHANGES_REQUESTED** [review]
bumping this per my last comment

**Pull request closed without merging**
