### PR TITLE
chore: rename project-registry to builder

### PR DESCRIPTION
**Pull request by codenamejason**
This renames `project-registry` with `builder`.

### CODE REVIEW

**Comment by hmrtn** [comment]
this is failing the fleek build here: 
```
Deploy started at 2023-02-06T22:02:*****2.587Z

2023-02-06T22:02:13.900Z: Limit of max concurrent builds reached. Waiting...
2023-02-06T22:03:15.477Z: Limit of max concurrent builds reached. Waiting...
2023-02-06T22:04:13.926Z: Limit of max concurrent builds reached. Waiting...
2023-02-06T22:05:13.891Z: Limit of max concurrent builds reached. Waiting...
2023-02-06T22:06:13.940Z: Deploy started
2023-02-06T22:06:15.795Z: Docker image: 'boudra/pnpm-node16:latest'
2023-02-06T22:06:15.795Z: Build command: 'pnpm install && pnpm build'
2023-02-06T22:06:15.795Z: Triggering build execution...
2023-02-06T22:07:03.663Z: /bin/sh: 1: cd: can't cd to /workspace/packages/project-registry
2023-02-06T22:07:27.100Z: Error occured during the build.
```

**Comment by codenamejason** [comment]
@gitcoinco/gpc-engineering we will need to update the production fleek setting to change the directory to `packages/builder` from `packages/project-registry`.

**Review by thelostone-mc — CHANGES_REQUESTED** [review]
- looks like it's removing files from contract folder
- we need to rebase with main cause it looks like a graph folder still exists here (which was removed in the graph folder migration PR)

**Comment by melissa-neira** [comment]
I defer my review to engineering 🚀

**Comment by gravityblast** [comment]
@thelostone-mc fixed now, it should be ready to be merged

**Review by boudra — APPROVED** [review]

**Review by thelostone-mc — APPROVED** [review]

**Review by sara554-beep — COMMENTED** [review]
@gravityblast

**Pull request merged**
