### PR TITLE
feat: update ge PreRoundPage design

### LINKED ISSUE #652: Updated GE application design
**User Story:**
As a potential grantee
I want to see the updated pre-round view
So that I can see the pretty design

**Acceptance Criteria**
- add start/end times in UTC
- update design of pre-round page to match Figma
- overlay box expands/scrolls for longer text 

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=3305%3A89904&t=BTd47ilAGgeCBye4-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
##### Description

As a potential grantee
I want to see the updated pre-round view
So that I can see the pretty design

##### Refers/Fixes

fixes #652

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]

**Comment by bhargavaparoksham** [comment]
@melissa-neira it should work now. Please check.

**Review by melissa-neira — CHANGES_REQUESTED** [review]
screencapture-bafybeibm7mk3heope6hprdguygnfai7uh2xdcu7dsnrz4qbi4vbufcijmq-on-fleek-co-2023-02-01-16_29_55
This is looking a bit off for me - is this happening to anyone else? the text isn't centered and there's a huge white space under the footer. Also, the gradient is horizontal but should be vertical. There's also a weird interaction happening when I hover over the button, it turns 2 different colors. Here's what the button should look like in its [default state](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=3305%3A89926&t=MPnPur9assgCKhgm-4) and its [hover state](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=3326%3A89979&t=MPnPur9assgCKhgm-4). The secondary text should also be a different color, refer to [Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=3305%3A89904&t=MPnPur9assgCKhgm-4)

**Comment by nfrgosselin** [comment]
I'm having the same issue as @melissa-neira. Additionally I'm seeing a weird line break on the date lines:
image

URL for reference: https://bafybeibm7mk3heope6hprdguygnfai7uh2xdcu7dsnrz4qbi4vbufcijmq.on.fleek.co/#/round/5/0x5b261391cfb80380c28eb3b0e39fdf96f8cdfb73

**Comment by thelostone-mc** [comment]
@melissa-neira / @nfrgosselin Pushed in a commit to address the changes

**Review by melissa-neira — APPROVED** [review]

**Review by nfrgosselin — APPROVED** [review]

**Pull request merged**
