### PR TITLE
feat: add token units drop down

### LINKED ISSUE #512: Add token units drop-down
**User Story:**
As a donor to a QF round
I want to be able to select the token to donate to my chosen products
So that I can spend tokens that I have in my wallet

**Acceptance Criteria**
GIVEN that I am on the Donation Builder
WHEN I look above the final donation
THEN I see the heading "Amount/Currency"
AND a drop-down menu with the default token for that round listed

GIVEN that I am on the Donation Builder
WHEN I click on the currency drop-down
THEN I see a list of eligible donation tokens for that round

GIVEN that I am looking at the currency drop-down
WHEN I click on a currency
THEN the drop-down closes
AND the currency I clicked is now selected in the drop down

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1055%3A27643)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
##### Description

As a donor to a QF round
I want to be able to select the token to donate to my chosen products
So that I can spend tokens that I have in my wallet

##### Refers/Fixes

fixes #512

### CODE REVIEW

**Review by melissa-neira — CHANGES_REQUESTED** [review]
The width of the drop-down box changes with every selection, let's make it a consistent size. The box should be 113px in width. See example here in [Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1862%3A69243)

**Comment by thelostone-mc** [comment]
@melissa-neira 113px causes the token. name to be hidden

image

**Comment by melissa-neira** [comment]
@thelostone-mc what do you suggest then? Is there a good size for the box that keeps the size consistent?

**Comment by thelostone-mc** [comment]
@melissa-neira I've set it to 130px and that seems to work

**Pull request merged**
